temp remove pypi-cli due to bug in upstream
There is a current open bug to resolve error:

    ImportError: cannot import name 'get_terminal_size' from 'click.termui'

See https://github.com/tiangolo/typer/issues/ 377