Revert "Update dependency docker-compose to v1.26.0"
This reverts commit a1c9e99cef6b51536dba849efd576c2b177e1349.

docker-compose 1.26.0 broket TLS verification.

If DOCKER_HOST is a non-TLS connection, such as:

    DOCKER_HOST=tcp://172.17.0.1:2375/

Then docker-compose aborts with:

    Traceback (most recent call last):
      File "/usr/bin/docker-compose", line 8, in <module>
        sys.exit(main())
      File "/home/user/.local/lib/python3.8/site-packages/compose/cli/main.py", line 72, in main
        command()
      File "/home/user/.local/lib/python3.8/site-packages/compose/cli/main.py", line 125, in perform_command
        project = project_from_options('.', options)
      File "/home/user/.local/lib/python3.8/site-packages/compose/cli/command.py", line 66, in project_from_options
        return get_project(
      File "/home/user/.local/lib/python3.8/site-packages/compose/cli/command.py", line 141, in get_project
        client = get_client(
      File "/home/user/.local/lib/python3.8/site-packages/compose/cli/docker_client.py", line 45, in get_client
        client = docker_client(
      File "/home/user/.local/lib/python3.8/site-packages/compose/cli/docker_client.py", line 141, in docker_client
        context = Context("compose", host=host, tls=verify)
    TypeError: __init__() got an unexpected keyword argument 'tls'