remove ruby-based pre-commit hooks for now to avoid error
The hooks that depend on ruby fail with error:

    ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /root/.local/pre-commit/repo*/rbenv-system/gems directory.

I need to figure out why `pre-commit install-hooks` fails with those.