show build metadata in container as env vars
As shown in the tests at
https://circleci.com/gh/jumanjihouse/docker-aws/3112#tests/containers/0

    [RUN] circleci config validate
    Error: 1 error occurred:

    * Config file is invalid:
      at workflows.jobs.0: workflows.jobs.0: Must validate one and only one schema (oneOf)
      at workflows.jobs.0: awscli_version: Additional property awscli_version is not allowed
      at jobs: description: Additional property description is not allowed
      at jobs: parameters: Additional property parameters is not allowed

This is mysterious because the code for that test is:

    if command -v circleci &>/dev/null; then
      # https://circleci.com/docs/2.0/local-cli/#validate-a-build-config
      run circleci config validate
    fi

This image currently does NOT have the circleci binary,
so what magic is happening on circleci to include it?